name: example
description: A minimal jaspr web app.
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  jaspr: ^0.16.3
  jaspr_provider:

dependency_overrides:
  jaspr_provider:
    path: ../

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.0
  webdev: ^2.7.7
