name: jaspr_provider
description: A wrapper around InheritedComponent to make them easier to use and more reusable.
version: 0.0.4
repository: https://github.com/Maksimka101/jaspr_provider

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.19.0
  jaspr: ^0.16.3

dev_dependencies:
  jaspr_test: ^0.16.3
  mockito: ^5.4.5
